name: Subbody Resonance Society
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11572
title: Subbody Resonance Society
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#564d0a'
    - '#887f36'
    - '#dfd682'
  brandStrength: 0.17425287724472582
  lightness: 0.5926347239874303
  saturation: 0.0018512019887566566
  rhythmicContrast: 1
purpose: []
